name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv==2022.4.8
        pipenv --python 3.7
        pipenv run python -m pip install pip==21.3.1 setuptools==59.6.0
        pipenv sync
        pipenv install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
